### ISSUE TITLE
Integration of Biomass maap data

### ISSUE THREAD

**Issue by santilland** [eurodatacube/eodash#1378]
Integrate datasets coming from biomass maap
https://earthdata.nasa.gov/maap-biomass/
Should be following:
- [ ] CCI Biomass 
- [ ] GEDI Gridded Biomass - still marked as not yet available, source unknown
- [ ] ICESat-2 Boreal 2020 
- [ ] NASA JPL 2020 
- [x] NCEO Africa 2017

All layers are quite slow loading and sometimes errors appearing for tiles, NCEO africa seems to load good, could be integrated

**Comment by AlessandroScremin** [comment]
@gmilcinski  @TonioF cc: @aapopescu @santilland 
I can't add Tonio Fincke to this issue...
In case someone could contact/add him?

We need to investigate if it is fisable for you to ingest these datasets, it seems that from NASA APi EOX is facing some issues and we would like to know if you could handle them to be ingested in EDC...

what do you think?

kr

Alessandro

**Comment by gunbra32** [comment]
As far as I understand the context, you are trying to integrate the WMS from NASA and are facing issues (or EOX when trying to integrate the service into the dashboard). To this end, we cannot help but you may rather want to contact NASA. 

Alternatively (this is what we did with the previous data sets), we could try to convert the data to zarr so that they could be integrated into and served by SH. For BIOMASS, this should be ok as we know the data but the other data sets require further investigation to understand the effort. Should we do so? Could EOX confirm that we should start this investigation?

**Comment by santilland** [comment]
After discussion with NASA it seems they will integrate the data into their own service (currently i think the issues are from the cci endpoint as it was with the sea ice datasets) and we will afterwards user their endpoint.
So no action required from you side @gunbra32 , we will use this ticket to track the status of integration of the NASA services.

**Comment by AlessandroScremin** [comment]
@aapopescu @santilland 

@aapopescu  should they start with the investigation ?

**Comment by santilland** [comment]
Closing this ticket, possible new datasets to be included in the future tracked here #1459
