### ISSUE TITLE
Load (and convert?) example data (from Austria) provided by Stefanie/ DLR

### ISSUE THREAD

**Issue by slumnitz** [eurodatacube/eodash#1584]
- [ ] Output vom model COG (Cloud optimized geotiff) - mehrere produkte (Solar flächen...)

**Comment by santilland** [comment]
I think current approach with vector data is working nicely, we can extract usefull statistics and visualize the data thanks to a geoserver instance. 
In order to possibly increase performance we will evaluate pre-computation of administrative zone aggregations, see https://github.com/eurodatacube/eodash/issues/1840 
I will close this issue, please @slumnitz reopen it if you consider there is still a discussion to be had in relation to this.
