### ISSUE TITLE
Update datasets

### ISSUE THREAD

**Issue by aapopescu** [eurodatacube/eodash#1591]
for RACE:

- [x] - TROPOMI (NO2, CO, CH4, SO2)
- [x] -  C3S Data : Humidity, temperature, wind U,V

For Trilateral:

- [x] - GEOGLAM
- [ ] - NASA CO2
- [x] - NASA NO2
- [x] - TROPOMI (NO2, CO, CH4, SO2)

**Comment by santilland** [comment]
I will write down the information i got for these collections as of today, please @AlessandroScremin let me know if this coincides with the data available on EDC. In any case it seems these latest datasets were added quite recently (i.e. last week) if not it seems SentinelHub was not returning updated responses through the WFS service for quite some time.

TROPOMI NO2 (AWS_NO2-VISUALISATION):
        "2022-08-01",
        "2022-08-08",
        "2022-08-15",
        "2022-08-22",
        "2022-08-29",
        "2022-09-05"
TROPOMI CO (AWS_VIS_CO_3DAILY_DATA):
        "2022-09-12",
        "2022-09-13",
        "2022-09-14",
        "2022-09-15",
        "2022-09-16",
        "2022-09-17",
        "2022-09-18"
TROPOMI CH4 (AWS_CH4_WEEKLY):
        "2022-07-25",
        "2022-08-29",
        "2022-09-05",
        "2022-09-12"
TROPOMI SO2 (AWS_VIS_SO2_DAILY_DATA):
        "2022-09-16",
        "2022-09-17",
        "2022-09-18",
        "2022-09-19",
        "2022-09-20"

For C3S if i understood correctly Alessandro you need to update your scripts to continue synchronization.
C3S Humidity (AWS_VIS_2MTEMPERATURE):
        "2022-01-01",
        "2022-02-01",
        "2022-03-01",
        "2022-04-01"
C3S wind U (AWS_VIS_WIND_U_10M):
        "2022-01-01",
        "2022-02-01",
        "2022-03-01",
        "2022-04-01"
seems to be equal to all


For trilateral:
GEOGLAM:
stac endpoint: https://staging-stac.delta-backend.com/collections/geoglam/items?limit=5000
latest date is "2022-05-01T00:00:00", matches with response from endpoint

NASA CO2: 
This still uses the "old" NASA access approach, there is a co2-mean collection in the STAC interface with which we could probably use to replace this one. But the new statistical api from NASA has not yet been implemented, this uses the old api.

NASA NO2 (no2-monthly): 
stac endpoint: https://staging-stac.delta-backend.com/collections/no2-monthly/items?limit=5000
there are some issues with this collection since the update done to the interface, it is being worked on by NASA

For TROPOMI data see above.

**Comment by AlessandroScremin** [comment]
@santilland 
YES they match what I have in Sentinel HUb

**Comment by santilland** [comment]
New issue opened for geoglam data #1634 
New issue opened for no2 data #1635
New issue opened for co2 data #1636
