### ISSUE TITLE
Harmonize legends -> collect information on ranges and colorscales used

### ISSUE THREAD

**Issue by santilland** [eurodatacube/eodash#1732]

**Comment by lubojr** [comment]
As for homogenization efforts:
We would go for something reproducible stored in the eodash repository, so that we can always find it and (re)generate new legends.
We would create a new JSON file with definition of min/max ranges, linear/logarithmic scale, name of colorscale used and auxiliary information (legend header etc.) as input to the script to generate the colorlegends using matplotlib.

This would mean we would go one by one through all defined indicators containing legends to create the JSON values and recreate their legends using the new approach and extend the script to handle all cases. We would also unify the output folder and legend file naming structure. We would then document the steps to generate a new legend.

**Comment by lubojr** [comment]
Addressed in #1799
