### ISSUE TITLE
CO AOI user defined timeseries

### ISSUE THREAD

**Issue by AlessandroScremin** [eurodatacube/eodash#1829]
**Describe the bug**
the timeseries generated with the user defined AOI is incomplete, but the maps/data are avaialbe.

**Desktop (please complete the following information):**
 - OS: windows
 - Browser chrome
 - Version 107

**Steps to reproduce**
I clicked on global CO maps from S5P pal. then selected an AOI over paris and get the chart. I noticed that from 27 october to 2 november the timeseries in the chart has missing values, but looking at the maps for the gapping period maps are availble.

**Expected behaviour**
When maps exist the data should be avaialbe in timeseries charts

**Screenshots**
![image](https://user-images.githubusercontent.com/65602207/204773645-16c93920-a0ab-4b4f-a695-a8ac4e6276cc.png)

It laso seems that timeseries for daily CO data is a 3 days averaged is it correct? if so it should be descrived somewhere as the maps are provided daily but timecharts are 3day

![image](https://user-images.githubusercontent.com/65602207/204776100-4518749c-785c-413d-a8fd-6494b5dedbe2.png)

**Comment by lubojr** [comment]
Note about 3day average added to chart axis in https://github.com/eurodatacube/eodash/commit/bb7a5319b502ba4da3416e7630146967645496a6 

As for availability of data, these are caused by overall spotty performance of sentinel hub /statistics requests - which would be another issue.

Some time ago there was a bug that following alert: 
![image](https://user-images.githubusercontent.com/19269667/206192357-623be028-4ff6-4846-96c5-1621931a1223.png)

was not shown when some requests timeouted - this was fixed recently together with unrelated changes.

**Comment by aapopescu** [comment]
Something for @gmilcinski :)
