### ISSUE TITLE
Add "N E S W" to aspect slider

### ISSUE THREAD

**Issue by patrick-griffiths** [eurodatacube/eodash#1865]
Simply add some indicator ticks for North (0 degree) East (90 degree) South (180) and West (270) 

![Image](https://user-images.githubusercontent.com/40148967/208140412-e5447703-a799-49dd-868c-8596ff164c2f.png)

**Comment by spectrachrome** [comment]
Hi Patrick,

as discussed, the range slider for the `aspect` value has now been replaced by a circular slider with marks for North, South, East and West directions. Please try it in the feature branch deployment and let us know what you think.

https://gtif-testing.eox.at/gtif_nesw_aspect_circular/

<img width="543" alt="Screenshot 2023-02-10 at 14 34 11" src="https://user-images.githubusercontent.com/94269527/218105273-8cd4127d-bdb3-4e20-99d2-110dde6ad6c5.png">

**Comment by lubojr** [comment]
Merged to demo -> Still possible to do minor updates @patrick-griffiths

**Comment by lubojr** [comment]
-> decided to just put ticks for now and leave the slider evolution for future improvements (and then we should include the possibility to allow selecting angle between two directions (NW -> NE for example - which would be 270 -> 360 AND 0 -> 90) which currently not even our style definition allows

**Comment by patrick-griffiths** [comment]
@lubojr we like the advanced aspect selection (did not get the chance to provide feedback earlier, sorry)!

**Comment by spectrachrome** [comment]
Due to implementation constraints, we've now decided to simply use two normal sliders along with a compass indicator and a textual degree range. This allows for easy rotation of the directional wedge while retaining its width. Furthermore, the aspect control now also shows data on the map if the wedge is rotated beyond 360 degrees and performance has been increased.

https://user-images.githubusercontent.com/94269527/219640585-797d16f4-6429-4882-8ff1-f4f107a04343.mp4

**Comment by patrick-griffiths** [comment]
@spectrachrome 

this two part slider takes up quite a bit of space. 
The one that was used previously (below) is a bit less intuitive, but more compact..

![Image](https://user-images.githubusercontent.com/40148967/221625079-305548fd-608e-4206-bd0b-ae9af7d5fbbb.png)

**Comment by spectrachrome** [comment]
@patrick-griffiths 

As the interaction with the previous slider was not very flexible, we'd like to avoid using it again, especially since you couldn't simply rotate around, and also not beyond 360 degrees. However, we do agree it's taking up a lot of space at the moment.

As an alternative, how about we update the current layout to make it more compact? Something like this:
<img width="529" alt="Screenshot 2023-02-28 at 15 22 34" src="https://user-images.githubusercontent.com/94269527/221885749-a6c8d6d0-45ef-48fb-8bb7-f937f5d246f1.png">

**Comment by spectrachrome** [comment]
GTIF's main branch has now been updated with a new, strictly horizontal version of the NESW aspect control:


https://user-images.githubusercontent.com/94269527/222702880-b2420b0f-8ba9-4e95-a028-fe1c093474a5.mov
