### ISSUE TITLE
Integrate new Jaxa timeseries data

### ISSUE THREAD

**Issue by lubojr** [eurodatacube/eodash#1921]
A new indicators from JAXA are created: 
database= eodash
Indicator --> table name
VITS --> VITS_Vegetation_Index_Timeseries
SMCTS --> SMCTS_Soil_Moisture_Timeseries
PRCTS --> PRCTS_Precipitation_Timeseries

**Comment by lubojr** [comment]
Added indicators to branch https://eodash-testing.eox.at/1791-1918-1773/ and created placeholders for stories

**Comment by santilland** [comment]
data is on trilateral deployment https://eodash-trilateral-testing.eox.at/1791-1918-1773/

**Comment by lubojr** [comment]
just configured to use a multiyear line chart, the same way as E10c

**Comment by lubojr** [comment]
@aapopescu We would need a story markdowns for following indicators on [2023-02-jaxa-data branch](https://github.com/eurodatacube/eodash/tree/2023-02-jaxa-data)

- [ ] SMCTS
- [ ] VITS
- [ ] PRCTS

**Comment by AlessandroScremin** [comment]
Dear 
@lubojr  
cc: @santilland @aapopescu 

data from Jaxa have been updated and now cover from January 2020 to December 2022

they are avaialbe at the following tables on eodash database:
PRCTS_Precipitation_Timeseries
SMCTS_Soil_Moisture_Timeseries
VITS_Vegetation_Index_Timeseries

these updated data have also an added value: the reference value,  to be displayed on the graph together with the actual value.
the structure is (as done also for N1 indicator)
measurement value + reference_description + reference_value 
 - eg:  xxx, Normalized Difference Vegetation Index [climatic value], [yyy] 

So that the timeseries show in the same chart the measurement values and the climatic values in square brackets.

the sub AOI (as it si quite long) has been provided only for the first record of each AOI_ID.

let me know if there are any issues with this.

kr

Alessandro

**Comment by lubojr** [comment]
@AlessandroScremin we have just integrated the reference value visualization of these three indicators as a tooltip on hovering over the points. I think it will be less confusing this way rather than adding 3 more lines with climatic value (which would also be extra implementation at the moment). Please have a look at https://eodash-trilateral-testing.eox.at/2023-02-jaxa-data/

@aapopescu We would just need some markdown description and we are good to merge? PR to staging is on https://github.com/eurodatacube/eodash/pull/2050

**Comment by AlessandroScremin** [comment]
@lubojr  Personally It is not clear to me why we are showing the 3 years one over the other and not as a timeseries...but maybe I'm missing some discussions about its visualisation...we can disucss it later today

**Comment by lubojr** [comment]
> @lubojr Personally It is not clear to me why we are showing the 3 years one over the other and not as a timeseries...but maybe I'm missing some discussions about its visualisation...we can disucss it later today

Agreed to reconfigure chart to use the single line for data and another parallel for reference value for all 3 years -> will replace the images in agri story
