### ISSUE TITLE
Add Bodenwertigkeitskarte as baselayer(s) for Energy transition datasets

### ISSUE THREAD

**Issue by santilland** [eurodatacube/eodash#1969]
They are vectortiles from https://bodenkarte.at/
Styled for:
Bodenwertigkeit -> Wertigkeit Ackerland

![Image](https://user-images.githubusercontent.com/4036819/216376918-04eaca6a-2fae-4f11-8f05-19a306c48839.png)

Additionally:
Bodenwertigkeit -> Wertigkeit Grünland could be added as another layer

**Comment by lubojr** [comment]
These two layers were added as optional baselayers in https://github.com/eurodatacube/eodash/commit/e9dd1764a69404402def796ab5ee98ab1fa514a0 in branch `gtif-bodenkarte-layer`
I would suggest to instead set them as optional overlays above the data layer because now all REP1-5 indicators are not semitransparent, so a baselayer is not seen at all. @santilland

**Comment by patrick-griffiths** [comment]
@lubojr this looks very good. Could we rename the baselayer entries to the following please: 

- Soil value - Cropland - bodenkarte.at
- Soil value - Grassland - bodenkarte.at

This way it give clearer credit to the creator the BFW

**Comment by lubojr** [comment]
> @lubojr this looks very good. Could we rename the baselayer entries to the following please:
> 
> * Soil value - Cropland - bodenkarte.at
> * Soil value - Grassland - bodenkarte.at
> 
> This way it give clearer credit to the creator the BFW

Done
