### ISSUE TITLE
Hydro reservoir dams min, max and current energy storage (dynamic).

### ISSUE THREAD

**Issue by santilland** [eurodatacube/eodash#2084]
https://github.com/eurodatacube/eodash/issues/1597

**Comment by santilland** [comment]
First dataset delivery received, integration approach needs to be discussed, meeting planned for friday 27 Apr.

**Comment by santilland** [comment]
Data partly ingested into geodb, integration into client as 2 separate indicators:
1. surface elevation monthly mean (for 3 big lakes) - 2 charts
2. SWE (extent) daily with s1 background + possibilty to also show the monthly comparison to other years plot - 4 charts

**Comment by santilland** [comment]
As lakes features might be difficult to find it might be interesting to check if we can use pointrenderer for the geoserver to create a sort of "overlay" layer with selectable point icons to help with selection

**Comment by lubojr** [comment]
Integrated in `gtif_staging` as a set of POIs.
Still left to decide if 3 special lakes should be split to another indicator.

**Comment by patrick-griffiths** [comment]
@lubojr this all looks very good. 

Only improvement recommendation would be: 
Could we dynamically link the time series graph with the date selection for the S1 or S2 visualization? 
So that the user could select a point in the time series graph and that observation is displayed in the map view? 


![Image](https://github.com/eurodatacube/eodash/assets/40148967/26af95d7-eebb-498b-9c69-403d9770a0f2)

**Comment by lubojr** [comment]
@patrick-griffiths This enhancement will be certainly valuable and is tracked in https://github.com/eurodatacube/eodash/issues/1735
