### ISSUE TITLE
Micro hydropower, annual power production potential (KW/year)

### ISSUE THREAD

**Issue by santilland** [eurodatacube/eodash#2085]
https://github.com/eurodatacube/eodash/issues/1597

**Comment by santilland** [comment]
First dataset delivery received, integration approach needs to be discussed, meeting planned for friday 27 Apr.

**Comment by santilland** [comment]
No data for micro hydropower yet, waiting on imputs

**Comment by santilland** [comment]
Important to show power generation as e.g. color to help find more important nodes

**Comment by lubojr** [comment]
@patrick-griffiths @kegro @santilland 

PR adding the dataset has been created - https://github.com/eurodatacube/eodash/pull/2292

Please have a look. Thank you

**Comment by patrick-griffiths** [comment]
I would suggest that we ask @kegro and Christian for feedback on this. 

From my side:
- I like the way the catchment is visualized. I would suggest to activate geoland basemap gelaende by default
- how about automating a zoom in to e.g. level 12, by click on a circle feature?
- the long list of attributes is a bit overwhelming: (1) units are unclear, (2) use km rather than m2, (3) round numbers to max 2 digits
- also as an alternative to this long list of attributes, a classical dashboard view to this could be nicer, so a panel on the right side that show bar and pie charts, rather than this long list of attributes

![image](https://github.com/eurodatacube/eodash/assets/40148967/f0c7cc14-382d-4a75-a255-a4f87fd0f248)

**Comment by lubojr** [comment]
Thank you for the feedback. All points make very much sense. We would therefore wait for other feedback as well and then integrate them in a bulk.
