### ISSUE TITLE
Add S2 data as overlay to hydro detections

### ISSUE THREAD

**Issue by santilland** [eurodatacube/eodash#2121]
Once added do not fill vector data but use color for outline so that s2 image can be seen better

**Comment by lubojr** [comment]
First WIP draft added in `hydro-s2-overlay-03-2023` 
Needs to be tested if does not break other parts of client.

Usage on this indicator in current form is not a good idea though, because dates are always end of month, which does not always yield cloudless S2L2A imagery. Dates would need to be updated to be of any added value to the user.

**Comment by santilland** [comment]
@patrick-griffiths important for your consideration. The dates in the current hydro dataset do not seem to match the dates from the actually used observation times (only the end day of each month was used), so it is not really possible to match the scenes currently.
We can add the functionality but it does not add much value right now.

**Comment by patrick-griffiths** [comment]
@kegro - we would like to provide overlays with S2 data for the hydro reservoirs. 
For this we would need a list a S2 image dates that were used for the water extent mapping. 
Could you take a look at this (see above)? 
https://gtif.esa.int/explore?x=1674632.59388&y=5891751.67411&z=14.47852&poi=Austria-REP4

**Comment by lubojr** [comment]
Integrated in gtif_staging
