### ISSUE TITLE
Enable comparison across regions/admin units

### ISSUE THREAD

**Issue by Patrick1G** [eurodatacube/eodash#2140]
across GTIF tools, the ability to compare regions is an important functionality. 
We should start thinking of how to enable this...

An example from the renewables would be that a user performs the site suitability analysis and then compares to districts/zaehlsprengel and investigates the related statistics (area, WPD, terrain, land cover, etc.). 

For selecting the units to compare it could be CTRL+click or two dropdown lists. 
The statistics could then be displayed on the right side pane, similar to what we have for sustainable cities (e.g. green roofs).

**Comment by santilland** [comment]
We have been discussing possible technical solution:
1. Introduce possibility to select multiple features (possibly by using a modifier, e.g. CTRL)
2. Render each selected feature in a new color
3. Show dataset on plot corresponding to feature color with same color
4. Update to also allow use of vector tiles for administrative zone selection
5. Consider if saving selection in url could be used to better share selections based on feature ids

**Comment by santilland** [comment]
Evaluate use of vector tiles for admin zones as complete geometry would no longer be needed and it might provide performance improvements

**Comment by patrick-griffiths** [comment]
@santilland any updates on this functionality? 
Lets discuss this also in the context of the "statistical summary tool" for raster science products

**Comment by lubojr** [comment]
Discussed first steps:

- [ ] Allow to configure which admin zones are displayed for dataset - move Austria dark overlay to a separate concept
- [ ] Configure which layer/s are usable for selection (include existing custom drawn area into this logic) - this unlocks the integration of aggregated mobility bin -> plot selection
- [ ] Allow multiple features (and their layer - as this allows mapping back to config) to be selected - consider how to trigger the multiselection on mobile!
- [ ] List multiple selected features in a simple list with option to easily delete them instead of having to repeat the selection in case of mistake
- [ ] Allow to change style of selected features based on index (to reuse in plot later on)
- [ ] Change admin zones to vector tiles from GeoServer

**Comment by lubojr** [comment]
@patrick-griffiths the latest state of the vector feature multiselection can be seen on https://gtif-testing.eox.at/multiselection-tooling-f/

PR on https://github.com/eurodatacube/eodash/pull/2205

**Comment by lubojr** [comment]
Decided to separate the tooltip and selection behavior into two separate configs

selection config will not implicitly enable tooltip behavior but will need to be configured by tooltip config

tooltip config will additionally enable a callback function accepting an OL Feature/RenderFeature and original mergedConfigData (for backreference to original indicator config) and returning a HTML content to be displayed

Solves point 2 from https://github.com/eurodatacube/eodash/issues/2183#issuecomment-1562422665 and heatExplorer

cc @santilland

**Comment by lubojr** [comment]
Can be closed?
