### ISSUE TITLE
RACE Truck Detection Indicator

### ISSUE THREAD

**Issue by patrick-griffiths** [eurodatacube/eodash#2142]
Lets integrate the RACE truck Detection Indicator in the GTIF mobility transition explore tools. 
It has high relevance and with the recent reprocessing for all of Europe monthly we should take advantage of this. 
The related tools for making spatial queries could be exposed as is if possible

**Comment by santilland** [comment]
Alessandro made a layer copy in sentinelhub accounts, we should be able to integrate the WMS now, there is still the question open on how/if we should also mirror the data in geodb

**Comment by AlessandroScremin** [comment]
@santilland and @patrick-griffiths 
from my side the layer as daniel said was provided. For what concern the geoDB, it is not clear what is expected from PLES side. there is only one database we manged the eodash, none database related to GTIF is under our control. 
So if there is the need to mirror/replicate the eodash database to one related to GTIF which I'm not aware of,, please @santilland provide me credentials. otherwise from my point of view it can be retrieved directly from eodash.

**Comment by santilland** [comment]
hello Patrick, this is still on me, we have another geodb instance for gtif, need to clarify what this means

**Comment by santilland** [comment]
Initial integration done, S2 layer requested to be added to SH gtif instance.
Test deployment under:
https://gtif-testing.eox.at/gtif_trucks/

I think we will probably need to change the displayed description telling the original source? with links to the race dashboard?
@patrick-griffiths could you propose a text?

**Comment by santilland** [comment]
Data has been integrated into demonstrator, closing issue
