### ISSUE TITLE
GTIF UI Panels overhaul

### ISSUE THREAD

**Issue by lubojr** [eurodatacube/eodash#2331]
Development will be happening on a branch `ui-panels-cat-changed-layout` - https://gtif-testing.eox.at/ui-panels-cat-changed-layout/

## Plan

0) Finish filling up the STAC Catalog of GTIF items
1) ~In long term update configurations to be on a per-layer basis, rather than per-tool (indicator POI) basis. This will help to more conveniently "overlay" different datasets eg solar + wind COGs, while still allowing their both sets of filters to be applied.~
2) Use the new Collapsable EOX Item Filter on the left side of UI (already seen on a branch) to allow two sets of filtering: Domains (maps back to the old domains, with the advantage of allowing a tool to belong in more than 1 domain easily) and Tools (mapping back to the old indicators)
3) ~Prepare a "special GTIF only" custom filter over all existing configured layer definitions to allow them to be added to the main map visualisation of current tool. UI-wise, this will be placed in the bottom left of the screen as a collapsable panel.~
4) Split the DataPanel on the right into collapsable Analytics and collapsable Information about the Tool (Data Info)
5) Analytics will contain the FilterControls (for example seen in Solar Energy) and all analysis results - charts for example
6) The styling selection dropdown will be moved on a per-layer-basis to the LayerControl, which is now placed in the bottom left of the page.

On mobile ALL the panels will be only tabs selectable in the bottom of the screen.

**Comment by silvester-pari** [comment]
@patrick-griffiths @mariangela-cataldo here's an initial mockup of how the re-arranging of UI elements would look like. 
- The previosuly so-called "Data properties" selection would be moved directly into the layer control to the corresponding layer; the reasoning behind this was that (although on a technical level very similar to the filtering tools) changing the visualization will probably be perceived by the user as changing "the data".
- The previous datapanel has been split up in two parts, "Info" and "Analysis", where both are optional. Analysis would include all charts, feature selections, filtering tools etc.

![image](https://github.com/eurodatacube/eodash/assets/26576876/a07bea10-6630-46be-9f96-5a3ab40c9551)
![image](https://github.com/eurodatacube/eodash/assets/26576876/96344212-2ba8-4538-9837-022435bdfcc5)
![image](https://github.com/eurodatacube/eodash/assets/26576876/dd1df0e6-6e23-453a-8241-8d800e2568dc)

Showing multiple tools at the same time as initially considered and as Lubo mentioned during the meeting is not part of this re-shuffle, as the config changes would need a large restructuring. This still could be considered in the future.

Please let me know what you think!

**Comment by mariangela-cataldo** [comment]
Thanks Sebastian for this updated design proposal!
I have a few questions to make sure I understood properly:

1 - Having the previous "data properties" moved into the layer control makes sense to me, though I wonder whether it would still be (technically) possible to split even further the layer into its components to allow for contemporary visualisation (e.g., to overlay PM2.5 and PM10 - though in this case we should have the possibility to use different colour bars)

2 - Splitting Info and Analysis sounds good, here's my question: how do you understand (within the Layers window on the left) which layer the Info window is referring to? will there be a way to highlight which layer is "selected"?

3 - You say it won't be possible to show multiple tools together, does this mean it won't be possible at all to overlay layers belonging to different tools (e.g. wind turbines with solar roofs?), or do you rather mean that it won't be possible to create a specific configuration of a tool, "save" it as a "personal layer" and analyse that with layers from another tool?

4 - Looking at the examples, I also wonder: it won't be possible to modify the visualisation by changing the lower and upper thresholds of visible data (as an additional option to modifying the opacity of the layer), correct? 

5 - Looking at the first example: as for the time series, shall the time slider be a separate window or could it be included under the specific layer (i.e. after opacity)?

6 - Looking at the second example: you have grouped layers into "overlay", "data" and "background". What each group includes should be immediately clear to the external viewer, and I wonder whether it is. My understanding would be: background and overlay are only for visualisation, while data layers are those which you can use for analysis. Is this correct? If so, shall we perhaps rename "data layers" as "analysis layers" or in some other similar way? In addition,from the dotted rectangles on the right side, I would think I have the possibility to move up and down layers changing visualisation: if this is the case, and the interpretation above of "overlay" and "background" is correct, does it really make sense to separate them in 2 different groups?

7 - Looking at the third example: will the analysis window contents be associated (i.e. change according) to the specific "selected" layer? 

8 - I am not sure I understood why we need to keep Domains and Tools in a single window and what are the implications in terms of UX. In principle, when we open the Explore Tools window, we should get a complete list of Domains from which to start, by selecting one and then having all the associated Tools visible... How will this work? Will the other domains just disappear? The overall navigation concept is not completely clear to me (will it be also possible to switch between analysis and stories from this window as in the Figma I shared?).

9 - From the graphical point of view, I believe you will implement the changes (to be aligned to the Figma) after the functionalities are implemented, correct?

Sorry for the long list of questions, you probably are doing things step by step and several of these things are already in your pipeline...

**Comment by mariangela-cataldo** [comment]
@silvester-pari 
Sorry, Silvester, not Sebastian!!

**Comment by silvester-pari** [comment]
Hi @mariangela-cataldo! We needed some time to process all your questions, we did our best to answer everything:

> 1 - Having the previous "data properties" moved into the layer control makes sense to me, though I wonder whether it would still be (technically) possible to split even further the layer into its components to allow for contemporary visualisation (e.g., to overlay PM2.5 and PM10 - though in this case we should have the possibility to use different colour bars)

Can you give us a visual example how this should look like if we have the same map features overlayed with different colors? For example PM2.5 and PM10. With the same color scale, the user couldn't see what's what, and with different color scales, the user would see a mix of colors without knowing what is what (which would require a third, "combined" color scale. Maybe I am mistaken, but from my understanding it makes only sense to show one of these visual datasets at a time.

> 2 - Splitting Info and Analysis sounds good, here's my question: how do you understand (within the Layers window on the left) which layer the Info window is referring to? will there be a way to highlight which layer is "selected"?

In short, the info and analysis refer to what the user currently sees on the map. In a longer answer, info and analysis sometimes refers to the currently selected tool, sometimes to a visualization of a layer. I agree that this might be confusing, but to clear this up we'd need to streamline how certain data is structured. We're trying to handle all the "special cases" as well as possible and hide complexity to the user. As to the "selected" layer - there is no such concept of having a map layer "selected", only visible and not visible layers.

> 3 - You say it won't be possible to show multiple tools together, does this mean it won't be possible at all to overlay layers belonging to different tools (e.g. wind turbines with solar roofs?), or do you rather mean that it won't be possible to create a specific configuration of a tool, "save" it as a "personal layer" and analyse that with layers from another tool?

Both won't be possible for now. Also here, it would be great to have a visual example of how combination of these datasets would make sense to the user. Regarding the "personal layer", I believe you're referring to https://github.com/eurodatacube/eodash/issues/2324, but that is not included in this current UI overhaul.

> 4 - Looking at the examples, I also wonder: it won't be possible to modify the visualisation by changing the lower and upper thresholds of visible data (as an additional option to modifying the opacity of the layer), correct?

Not 100% sure what you are referring to with modifying lower and upper thresholds, but if this is currently available in the data panel (for example Nitrogen Dioxide Tropospheric column content in the NO2 tool), then this would still be part of the new "analysis" panel; we won't add/remove any functionality there.

> 5 - Looking at the first example: as for the time series, shall the time slider be a separate window or could it be included under the specific layer (i.e. after opacity)?

Time slider would stay the same as it is now (see mockup).

> 6 - Looking at the second example: you have grouped layers into "overlay", "data" and "background". What each group includes should be immediately clear to the external viewer, and I wonder whether it is. My understanding would be: background and overlay are only for visualisation, while data layers are those which you can use for analysis. Is this correct? If so, shall we perhaps rename "data layers" as "analysis layers" or in some other similar way? In addition,from the dotted rectangles on the right side, I would think I have the possibility to move up and down layers changing visualisation: if this is the case, and the interpretation above of "overlay" and "background" is correct, does it really make sense to separate them in 2 different groups?

Sure, we can rename them to "analysis layers", that's a good idea. We can also disable the sorting functionality to reduce complexity. So background layers would always be underneath, and overlay layers would always be on top.

> 7 - Looking at the third example: will the analysis window contents be associated (i.e. change according) to the specific "selected" layer?

As mentioned in 2), sometimes the analysis panel refers to the tool (when there are no visualizations to choose from), sometimes to the chosen visualization of a layer. Again, we won't add/remove any functionality here, just re-organize the placement within the UI.

> 8 - I am not sure I understood why we need to keep Domains and Tools in a single window and what are the implications in terms of UX. In principle, when we open the Explore Tools window, we should get a complete list of Domains from which to start, by selecting one and then having all the associated Tools visible... How will this work? Will the other domains just disappear? The overall navigation concept is not completely clear to me (will it be also possible to switch between analysis and stories from this window as in the Figma I shared?).

The approach is to offer an easy-to-use navigation through the hierarchy which is Domains -> Tools. So each Domain has a List of Tools (a Tool could also be part of more than one Domain if I understand correctly). The user will be able to browse through domains and see all the associated tools; maybe this will become clearer if we have more datasets migrated to the new format.

Regarding switching to the stories - I guess this is an additional discussion we can have, but the current changes would not affect the story navigation.

> 9 - From the graphical point of view, I believe you will implement the changes (to be aligned to the Figma) after the functionalities are implemented, correct?

What is still planned is to enable opening/closing of the panels and showing their titles ("Domains & Tools", "Layers", "Info", "Analysis") and the mobile view (all the panels become "tabs" on mobile).

> Sorry for the long list of questions, you probably are doing things step by step and several of these things are already in your pipeline...

Let's take things step by step, if we try to change everything at once then we will not manage to do anything :-)

> Sorry, Silvester, not Sebastian!!

No worries at all ;-)

**Comment by mariangela-cataldo** [comment]
Hi @silvester-pari, 

thank you for the additional ideas, which go though quite far away from what proposed time ago through the Figma design and we are already working on...  
Better to keep building on the same track we are on.

Here is a follow up on the previous discussion thread. Please find my replies in bold, point by point (sorry, I am not very familiar with the use of github, I hope various text pieces don't get mixed up).

> 1 - Having the previous "data properties" moved into the layer control makes sense to me, though I wonder whether it would still be (technically) possible to split even further the layer into its components to allow for contemporary visualisation (e.g., to overlay PM2.5 and PM10 - though in this case we should have the possibility to use different colour bars)
Can you give us a visual example how this should look like if we have the same map features overlaid with different colors? For example PM2.5 and PM10. With the same color scale, the user couldn't see what's what, and with different color scales, the user would see a mix of colors without knowing what is what (which would require a third, "combined" color scale. Maybe I am mistaken, but from my understanding it makes only sense to show one of these visual datasets at a time.

**Let’s say you have the possibility to visualise PM2.5 in a red-only colour bar and PM10 in a blue-only colour bar: once you overlay the two layers with a reduced opacity, you should still be able to distinguish areas with higher values of one or the other variable.**

> 2 - Splitting Info and Analysis sounds good, here's my question: how do you understand (within the Layers window on the left) which layer the Info window is referring to? will there be a way to highlight which layer is "selected"?
In short, the info and analysis refer to what the user currently sees on the map. In a longer answer, info and analysis sometimes refers to the currently selected tool, sometimes to a visualization of a layer. I agree that this might be confusing, but to clear this up we'd need to streamline how certain data is structured. We're trying to handle all the "special cases" as well as possible and hide complexity to the user. As to the "selected" layer - there is no such concept of having a map layer "selected", only visible and not visible layers.

**Fine, I wonder whether having a “shaded” background to the related name of the layer (or the name of the tool) – in the respective windows – would not help cleaning this likely confusion. You can see what I mean in the Figma.**

![image](https://github.com/eurodatacube/eodash/assets/115264145/0ef7f7c2-a5d5-4acf-a0da-f98daec4de1d)

> 3 - You say it won't be possible to show multiple tools together, does this mean it won't be possible at all to overlay layers belonging to different tools (e.g. wind turbines with solar roofs?), or do you rather mean that it won't be possible to create a specific configuration of a tool, "save" it as a "personal layer" and analyse that with layers from another tool?
Both won't be possible for now. Also here, it would be great to have a visual example of how combination of these datasets would make sense to the user. Regarding the "personal layer", I believe you're referring to [#2324](https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Feurodatacube%2Feodash%2Fissues%2F2324&data=05%7C01%7CMariangela.Cataldo%40ext.esa.int%7C11476c44dd29439b090e08dbc9992032%7C9a5cacd02bef4dd7ac5c7ebe1f54f495%7C0%7C0%7C638325431735106791%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=DsH2EQ1GHElk4iJ6LiDsx6dxCBO1iLsbzXfEOTdVGyw%3D&reserved=0), but that is not included in this current UI overhaul.

**Understood. I leave setting the priority of having the possibility to create a custom layer (and add it to the layers panel) to @patrick-griffiths**  

> 4 - Looking at the examples, I also wonder: it won't be possible to modify the visualisation by changing the lower and upper thresholds of visible data (as an additional option to modifying the opacity of the layer), correct?
Not 100% sure what you are referring to with modifying lower and upper thresholds, but if this is currently available in the data panel (for example Nitrogen Dioxide Tropospheric column content in the NO2 tool), then this would still be part of the new "analysis" panel; we won't add/remove any functionality there.

**Clear, understood.**

> 5 - Looking at the first example: as for the time series, shall the time slider be a separate window or could it be included under the specific layer (i.e. after opacity)?
Time slider would stay the same as it is now (see mockup).

**Understood. To me it would fit better under the specific layer though.**

 

> 6 - Looking at the second example: you have grouped layers into "overlay", "data" and "background". What each group includes should be immediately clear to the external viewer, and I wonder whether it is. My understanding would be: background and overlay are only for visualisation, while data layers are those which you can use for analysis. Is this correct? If so, shall we perhaps rename "data layers" as "analysis layers" or in some other similar way? In addition,from the dotted rectangles on the right side, I would think I have the possibility to move up and down layers changing visualisation: if this is the case, and the interpretation above of "overlay" and "background" is correct, does it really make sense to separate them in 2 different groups?
Sure, we can rename them to "analysis layers", that's a good idea. We can also disable the sorting functionality to reduce complexity. So background layers would always be underneath, and overlay layers would always be on top.

**I would personally keep the possibility to change the order of layers and rather group layers in 2 groups: those for analysis ("Analysis products") and those for visualisation ("Supporting layers"). This is reducing complexity from my point of view.**

> 8 - I am not sure I understood why we need to keep Domains and Tools in a single window and what are the implications in terms of UX. In principle, when we open the Explore Tools window, we should get a complete list of Domains from which to start, by selecting one and then having all the associated Tools visible... How will this work? Will the other domains just disappear? The overall navigation concept is not completely clear to me (will it be also possible to switch between analysis and stories from this window as in the Figma I shared?).
The approach is to offer an easy-to-use navigation through the hierarchy which is Domains -> Tools. So each Domain has a List of Tools (a Tool could also be part of more than one Domain if I understand correctly). The user will be able to browse through domains and see all the associated tools; maybe this will become clearer if we have more datasets migrated to the new format.

**Would you please show a graphical example with all domains/tools? I am afraid we might end up having a long list in that window and no complete clarity in what we are looking at… but it may be my not full understanding of what you have in mind here.**

> Regarding switching to the stories - I guess this is an additional discussion we can have, but the current changes would not affect the story navigation.

**I see. This is not ideal though since the current navigation to stories gives them very little visibility and might not perform too well when more stories are added.**

> 9 - From the graphical point of view, I believe you will implement the changes (to be aligned to the Figma) after the functionalities are implemented, correct?
What is still planned is to enable opening/closing of the panels and showing their titles ("Domains & Tools", "Layers", "Info", "Analysis") and the mobile view (all the panels become "tabs" on mobile).

**No fine tuning of fonts/colours/icons then?**

**Comment by patrick-griffiths** [comment]
@silvester-pari 
just some quick general feedback, @mariangela-cataldo will provide more details, and we can discuss on Monday: 
- I like the split in the three panels
- for consistency the time slider should go into layer controls or analysis panel   
- to circumvent the complexities of "combining tools" we suggest adopting the "custom layers"concept, where users can perfom an interactive analysis (e.g. wind power filtering) and then "freeze the outcome"as a custom layer than can be added to the "analysis products" or "basemaps" panel (FYI & TBD "custom layers" may include non raster layers e.g. wind turbine BBs)
- categorization of layers control groups should consider (1) "analysis products" and (2) "supporting layer". "Custom layers" can then be added to either of those by the user..
- custom color bars and raster value stretches customization will be a nice feature but can have a bit lower priority for now

**Comment by silvester-pari** [comment]
@mariangela-cataldo here's the flat tools list I showed today for your consideration: https://codepen.io/silvestro1/full/ExGBYbO

In the meantime, I am still researching following your comment on "tools being layers" and how to show this in the UI.

**Comment by lubojr** [comment]
@mariangela-cataldo @patrick-griffiths 
We wanted to briefly confirm if we can proceed with the separation of configurations into the individual flat tools as shown in the link above from Silvester.

**Comment by mariangela-cataldo** [comment]
@lubojr @silvester-pari @patrick-griffiths 
Hi there! Yes, we had a short discussion about it with Patrick too yesterday and we confirm we can proceed with the separation of the configurations - We are going through the current version of the UI in the meanwhile to also have a look at the text fine-tuning which might be needed

**Comment by mariangela-cataldo** [comment]
@lubojr @silvester-pari as for the icons to be used within the LAYERS panel, since the info icon used for the legend might be misleading, may you use:

- the "drop" for the layer legend
- a new icon for the opacity (e.g. something like https://static.thenounproject.com/png/95968-200.png or https://static.thenounproject.com/png/95968-200.png)

For the post-BiDS modifications then we may foresee to keep having the info icon as a third icon associated to the layer, to open the layer-specific information panel. To be discussed in our next meetings.

**Comment by silvester-pari** [comment]
@mariangela-cataldo as we are using material design icons, would something like this be ok for the opacity? https://pictogrammers.com/library/mdi/icon/circle-opacity/

**Comment by lubojr** [comment]
@mariangela-cataldo This is really the branch we are working on and that we were showing. Could you please try anonymous window of a browser? It seems there are might be some caching issues.
For me https://gtif-testing.eox.at/ui-panels-cat-changed-layout/ shows newest content.
Generally there are some minor tasks left on https://github.com/eurodatacube/eodash/issues/2347#issuecomment-1785008631 but no UI changes planned anymore. The video could be already taken on this branch. I plan to merge it to production GTIF today or during the weekend.

**Comment by lubojr** [comment]
> @lubojr Sorry Lubo, it looks like nothing changes when I use an anonymous window either (neither Chrome nor Firefox). I can only see the left panels with domains only - no tools, no layers...

Fixed by adding scroll for smaller screens.

**Comment by lubojr** [comment]
I think the UI Panels overhaul is now finished and we should tackle possible remaining points in separate issues.

**Comment by mariangela-cataldo** [comment]
OK, we'll close then this issue and the #2103 and create a new one to tackle remaining points
