### ISSUE TITLE
Greenland datasets

### ISSUE THREAD

**Issue by AlessandroScremin** [eurodatacube/eodash#2350]
New datasets for Greenland. They are the same as for Antarctica, but on the North Emisphere. The names and legenda are the same of the antartica. Only band name is changing.

You can find the new datasets IDs as follow: 
 
ID: VIS_4D_GREENLAND_DAYS
6868b841-2c93-4a7d-bf0b-2f11c24bf9dd
ID: VIS_4D_GREENLAND_END
7bbcfb29-3260-466d-bdb6-da517019edd9
ID: VIS_4D_GREENLAND_ONSET
b110e14f-fb03-4143-ba57-587bd91a40be
ID: VIS_GREENLAND_MELTMAP
0b7572ec-4c4e-4fe5-9dae-ccc10241889e

**Comment by lubojr** [comment]
@AlessandroScremin Could you please try to create the Collection definition files for the STAC definitions as documented in https://github.com/eurodatacube/eodash-catalog/wiki and in email threads from Daniel?

We should already try gradually integrating the new datasets in this way instead of us defining global indicators in the configs.

**Comment by lubojr** [comment]
Is integrated in production catalog and staging eodashboard.org. Closing the issue.
FYI @aapopescu @santilland
