### ISSUE TITLE
New Indicaotr: E13d

### ISSUE THREAD

**Issue by AlessandroScremin** [eurodatacube/eodash#413]
Airplanes counts over te Airport area. 
THe values are provided one value averaged per month . So every record in the CSV represent a month.
THere is also a geojson per AOI , and in IT you can find all the points for each acquisition.

TO clarify the CSV has one value per month (an average) so we need siply to display this value and the reference. THe Geojson has all the acquisition from sentinel2 for the assigned AOI. 
So the requirement is to get the source image from the date in the Geojson and overlay the points in the geojson.   

ex: 
CSV 
AOI10 ..........month July. 2020, 20 airplanes  reference period 2019 ............... no subAOI ....

E13C_AOI10_deliverytime.geojson
2020-0712T12:00:00, oneairplane coordinates
2020-0712T12:00:00, seconfplane coordinates
2020-0715T11:00:00, oneairplane coordinates
2020-0715T11:00:00, seconfplane coordinates
2020-0715T11:00:00, thirdplane coordinates
2020-0722T15:00:00, oneairplane coordinates
....
SO for one Satellite acquisition they could have detected more than one airplane in the area covered.

As soon as data are available I will poeovide them

**Comment by santilland** [comment]
EOX to provide conceptual csv / data similar to what is done with ships or points from sistema data.
Propose structure to data providers / science team to see if they can adapt to this structure.

**Comment by Schpidi** [comment]
@AlessandroScremin FYI, E13c is already taken for "Number of Ships in Port" in the trilateral versoin.

**Comment by Schpidi** [comment]
PR in #609

**Comment by lubojr** [comment]
@AlessandroScremin Version with monthly entries was merged to production. In order to show individual entries in a tabbed manner a following suggestion was made internally: 

E13d indicator gets split into two versions in a conceptually similar way as water quality time series vs maps.
First will be the E13d.csv - charts with data that come from csvs - monthly entries. Almost no change in data needed there at all. There will be no EO-data button, as that is dependent on having same times. So `EO Sensor` and `Input Data` fields are to be deleted from data.

E13d_detections.csv - map data with all individual time entries coming from detections. Their respective S2 scenes will be referenced automatically. This will need the change of the detections from monthly to individual files per time entry, but the times themselves will be extracted "in addition" into a new csv. The csv will need to have following fields filled:
- AOI (needs to be different than in E13d.csv), for example changed by one last digit
- Country
- AOI_ID (will need to similar as in E13d.csv, but with `a` letter added to it, for example - ES14 -> ES14a
- City (matching E13d)
- Site Name (matching E13d)
- EO Sensor (taken from E13d)
- Input Data (taken from E13d)
- Update Frequency (taken from E13d)
- Indicator code: `E13d`
- Time (individual time entries)
- Sub-AOI - (taken from E13d, can be only on first entry in csv for that AOI)
Additionally geojson features need to have common naming with the `a` inside AOI_ID - for example `E13b_DE6a_20191221T103657.geojson`

Would this further approach be okay ?
