### ISSUE TITLE
N4a Greece Aspropyrgos new data and visualisation

### ISSUE THREAD

**Issue by AlessandroScremin** [eurodatacube/eodash#420]
N4a for Aspropyrgos.
CSV file as for N4a (caserta).
There is the inforamtion of total waste area for the region, and then  there is the information for the type of material.
one row for waste, one for metallic waste, one for plastic, one for mized, and one for soil.

We should display the graph as stacked pile of all materials, distinct by colour.

csv is in attachment.

THen there is the geojson with the all the sites within the AOI for which the differt type of material are located and the areas that changed between dates (geojson in attachment)

[Na4_PlanetekHellas_20200709_material.zip](https://github.com/eurodatacube/eodash/files/5002346/Na4_PlanetekHellas_20200709_material.zip)

**Comment by AlessandroScremin** [comment]
Dear @aapopescu @Schpidi 

Here I added to file to understand how to display them....with both json and csv....

I was waiting for your feedback....

I opened the discussion here...but if you prefer I will upload the data...roa t least the CSV....

let me know

**Comment by Schpidi** [comment]
@aapopescu do you want us to raise the priority on this and add it to the spreadsheet?

**Comment by aapopescu** [comment]
@Schpidi this indicator should not require new feature development

**Comment by Schpidi** [comment]
It should not be too much I agree but this stacked rendering ("We should display the graph as stacked pile of all materials, distinct by colour.") would be the first time that we don't have a single value for an entry but multiple if I'm not mistaken.

**Comment by aapopescu** [comment]
@AlessandroScremin , FYI

@Schpidi, @santilland for this indicator we will use the same graph as for E10a1, but instead of comparing 2019 with 2020 we will compare 2 dates:

2020-02-26 and 2020-05-20

On the EO Data, @lubojr, we will use the Geoglam implementation. We will display the areas and hovering over each area will display the area in sq km and the waste type. 
There will be 3 maps with the following dates (to be used also in the time bar): 
GR_WasteActivity_Level1_3_02_20 ----->>> 2020-02-26
GR_WasteActivity_Level1_3_05_20 ----->>> 2020-05-20
GR_WasteActivity_Level4_Changes ----->>> 2020-05-20 compared to 2020-02-26 

For the third one we can use the approach in the Slowdown Proxi Maps https://www.eodashboard.org/?poi=PE01-N7 


![image](https://user-images.githubusercontent.com/35488732/92079605-74f5f000-edc0-11ea-86e3-1a514a0926fa.png)

We will use a new code for this indicator because we need this different approach. 
Instead of N4a = Land fill sites: Waste volume changes
we will use
N4c = Land fill sites: Waste area changes

**Comment by aapopescu** [comment]
Csv is here:
https://github.com/eurodatacube/eodash-data/blob/master/data/N4c.csv

**Comment by lubojr** [comment]
Easiest to implement chart implementation to be evaluated with @santilland (no new data will come). Earlier date is reference, newer date is "data". Data have 4 + 1 (total) different waste types to be differentiated. 
The percent change of values in two dates is very small (~1%)
Regarding the map, we need to find a workaround for "difference" time entry. @lubojr Ideally a third time will be added artificially, but this needs to be reviewed regarding the chart implementation.

**Comment by santilland** [comment]
Configured visualization for N4c in branch N4c, visualization looks like the following
![image](https://user-images.githubusercontent.com/4036819/93229782-42aca100-f777-11ea-85ea-400cbe04b233.png)

**Comment by AlessandroScremin** [comment]
Is it possible to add new date? I received a new set of records for a new date (obtained with different Data source)  with same reference date of 2nd february

So we can see some more differences...at the moment the differences are very low and the graph looks the same...of course it is due to source values....

could we try to add the third day as pull I made few minutes ago? https://github.com/eurodatacube/eodash-data/pull/176

**Comment by Schpidi** [comment]
![Screenshot from 2020-09-18 08-53-27](https://user-images.githubusercontent.com/482265/93565950-7c0a2a00-f98c-11ea-95b6-77176f30a188.png)

**Comment by Schpidi** [comment]
implementation is merged to staging

**Comment by AlessandroScremin** [comment]
@lubojr @aapopescu 

here in atatchment the missing geojsons...
one for the lev 3 waste (single waste type, as we have also for february abnd may)
compare changes february with june
GR_WasteActivity_Level4_Changes_052020_062020.geojson

**Comment by lubojr** [comment]
Implementation done, except for missing image for deimos observation - related issue https://github.com/eurodatacube/eodash-data/issues/185 
I suggest closing this issue.

**Comment by AlessandroScremin** [comment]
@lubojr 

here the possible explanation of the issue
https://github.com/eurodatacube/eodash-data/issues/185#issuecomment-705517322
