### ISSUE TITLE
Switch ESA NO2 data source from S5p-PAL to EDC 

### ISSUE THREAD

**Issue by aapopescu** [eurodatacube/eodash#447]
@JPatruno @gmilcinski 

create layer for TROPOMI NO2 maps 
update url in esa.js and trilateral.js for NO2 - TROPOMI global indicator (N1-ESA)

**Comment by gmilcinski** [comment]
@JPatruno - can you update me on the status of NO2 ingestion? I believe the collection ddec1c8f-18d4-4189-ac5a-e279bb77323a was used but unless I am mistaken, it has not been updated for the last few weeks.

**Comment by JPatruno** [comment]
Hi all, 
the layer (Name: NO2 - visualisation, ID: NO2) has been created but we're having some troubles for making the layer visible in the EO browser. 
However, we have created a new collection (8a75088b-ab9e-4d4f-8d13-82fefc7e006e) including also weights of the data and this collection is updated automatically every two weeks. As expected, the latest two acquisitions have been ingested (2020-07-20 and 2020-08-03) in the new collection.
Once the layer will be visible in the EO browser then it has to be configured and it will be possible to switch to EDC.

**Comment by gmilcinski** [comment]
Hi Jolanda,
could you be more specific on what kind of problems you have?
I tried visualising layer in EO Browser and it worked without a problem (note that EO Browser will ask you to zoom in as the app itself is not expecting data at such low resolution; still, it will work).
I then also tried to load the WMS in QGIS and it works there as well. 
See screenshots. 

<img width="1335" alt="Screenshot 2020-08-11 at 19 02 47" src="https://user-images.githubusercontent.com/16798351/89926709-860a7180-dc05-11ea-877d-a173731cc317.png">


<img width="1440" alt="Screenshot 2020-08-11 at 19 02 40" src="https://user-images.githubusercontent.com/16798351/89926635-67a47600-dc05-11ea-84fc-b833d57208f7.png">

**Comment by JPatruno** [comment]
@gmilcinski Yes, now I can see it, it works also for me.

@Schpidi could you please update the layer (Name: NO2-visualisation, ID: NO2) configuration in order to point to this WMS endpoint: https://shservices.mundiwebservices.com/ogc/wms/163db53d-e8b9-4513-b1ec-453ea722fcf3 ?
Thank you very much.

**Comment by Schpidi** [comment]
@JPatruno do you really want to introduce another sentinel hub instance? I thought the goal was to have all layers under the same one?

**Comment by JPatruno** [comment]
@Schpidi 
Hi Stephan, 
we have one collection for the water quality data and we cannot mix it with air quality. There was an old collection we used for airquality for the trilateral hackathon, but now data format has changed so we used a new one. The one used for the trilateral hackathon, if used anywhere in the dashboard, can be substituted with this new one

**Comment by Schpidi** [comment]
@JPatruno not sure I follow. we're using plenty of layers (cf. https://github.com/eurodatacube/eodash/blob/staging/app/src/config/esa.js#L210) all coming from the same sentinel hub WMS instance. Could we add this layer there as well?

**Comment by Schpidi** [comment]
@JPatruno any updates on this? do you want us move forward and add a second sh id or are going to make the layer available at the one we're already using?

**Comment by JPatruno** [comment]
@Schpidi sorry for being late with this issue. 
We have added the layer where we have all the others, the ID is NO2-Visualisation. 
Could you please check if you see the layer? Thanks

**Comment by lubojr** [comment]
We have checked the new layer and on both instances, it works fine. Update has been made to staging. Now both trilateral and race dashboard use EDC tropomi data. @aapopescu @JPatruno

**Comment by aapopescu** [comment]
@Schpidi @AlessandroScremin note the s5p-PAL has changed the frequency of update for the maps from 1 week to 2 days

**Comment by lubojr** [comment]
Only for newly created dates or also retrospectively?

**Comment by Schpidi** [comment]
Now that we're using the EDC WMTS service we need to make sure that we properly synchronize on this update. @lubojr @AlessandroScremin

**Comment by lubojr** [comment]
Correct. I have checked all the currently shown dates in currently visualized weekly intervals and they are properly ingested and shown. So whenever the new dates ingested in EDC should have a different frequency (or retrospectively, the older ones) to be shown in the app, please ping us on slack. @AlessandroScremin @aapopescu

**Comment by AlessandroScremin** [comment]
I have two comments:
1) @Schpidi @lubojr  yesterday you showed two layers, one linked to NO-VISUALISATION layer and another one from EDC and we noticed the differences in color streching. In NO-VISUALISATION layer we used the same color script used for the Hackaton SPace APP. SO COuld you please tell me which layer are you comparing so that we can see the two different scripts?

2) @aapopescu I checked the status of the PDGS site provided us. In it there several products: day, fortnight,Month. We were requested to ingest into EDC (by Christiano Lopez) the fortnight products that is a 2weeks window with new product created every week (but we are ingesting it it biweekly). 
So if they are moving from 1 week to 2 days, at the moment these products are not avaialbe into the site. In https://maps.s5p-pal.com/ we can find only day, fortnight and month products.

If you prefer we can discuss about the new requirements once these data will be avaialbe. Do you have some othe rinfo? 
 
Alessandro

**Comment by AlessandroScremin** [comment]
@aapopescu @Schpidi 

Wait a moment. What products are you talking about. THe global indicator in the dashboard is not the map we are providing or at least the dates are not the same:
eg: in EDC in configuration [NEW] S5P-NO2
the dates are these ones in image (one value every two weeks, no overlay of timeframe
 ![image](https://user-images.githubusercontent.com/65602207/92896142-693ba680-f41c-11ea-8f4a-50560819697d.png)

but in the dashboard you use different products with overlay 
![image](https://user-images.githubusercontent.com/65602207/92896714-e830df00-f41c-11ea-858f-b5eb95d99f75.png)

 Where are you gathering these products?

**Comment by lubojr** [comment]
@AlessandroScremin I did not modify the times for the configurations, I thought it was ported from s5p-pal to EDC 1 to 1, so I left the dates. Layername that we use is `NO2-VISUALIZATION`. The dates in dashboard are created as 14-day long weekly intervals: https://github.com/eurodatacube/eodash/blob/staging/app/src/config/esa.js#L371 while for sending WMS request, we use the first date of the interval (start) https://github.com/eurodatacube/eodash/blob/staging/app/src/config/esa.js#L382 

If we should use different dates/intervals please give us a list of them, as we are not yet fetching the available dates from SH API.

**Comment by gmilcinski** [comment]
Not sure if relevant, but do note that you can easily get dates from SH using Catalogue API:   
https://docs.sentinel-hub.com/api/latest/api/catalog/#distinct  
@AlessandroScremin - which collectionID should be used? (there are quite a few existing now, it might make sense to clean them up to avoid confusion)

**Comment by AlessandroScremin** [comment]
@gmilcinski 
in the NO-VISUALISATION layer you have also the collection ID it refers to. in any case It is
"8a75088b-ab9e-4d4f-8d13-82fefc7e006e"

@lubojr  the time interval is fine 15 days, but it is provided biweekly, as agreed.  So my suggestion is to start from the date in the EDC (see image), and go back of 15 days. So that for each image you have the right interval. Let me know if you need this date to be updated somehwere...eventhough the proposal of @gmilcinski  could be a solution. 
![image](https://user-images.githubusercontent.com/65602207/92903654-870c0a00-f422-11ea-918b-00f3ace9a7ad.png)

**Comment by Schpidi** [comment]
@AlessandroScremin yesterday we were comparing the current production and staging versions. Production uses the S5p-PAL project offered service directly whereas staging uses the layer provided by you.

I propose to put the production deployment on hold until we have agreed on the time interval to use. I'd find it kind of a regression moving from weekly updates (with 14 days input) to fortnightly ones. In any case, with the new 2-day update interval this is an entirely new discussion. @aapopescu what do you think about the time interval?

**Comment by AlessandroScremin** [comment]
@Schpidi 
THnaks for feedback.
At this point I understand now you were already retirving product from S5P PAL and not from S5P NO2 COnfiguration.  
SO they are different in colors intensity because it seems we are not using the same color scale. We used the same color definition provided for teh NASA-JAXA-ESA Hckaton for SpaceAPP...so it is just to understand which color scale we would like to use. In case I think the custom script in EDC can be converted into the colors you are using (you should have the parameters).

For what concerns the Dates @aapopescu , I talked with my team and the agreement with Cristiano Lopez was to ingest one produt every two week and not the one every week, of course if requirements changed we can change the update frequency accordingly if needed.
But It seems to me there is a duplication of effort so far. If we want to use EDC then we can keep the products from our maps and decide the color scale), otherwise EOX alreay put in place the workflow to collect the data. In both cases the source of data is the same. if I'm not wrong:   https://maps.s5p-pal.com/


For waht concern the 2days as said I can't see the product online yet....

kr

ALessandro
