### ISSUE TITLE
update JAXA Water Quality Maps

### ISSUE THREAD

**Issue by aapopescu** [eurodatacube/eodash#448]
@lubojr @Schpidi 
Please update JAXA WQ maps for "Total Suspended Matter"

Data should be available for Tokyo, Nagoya, Osaka, Venice. 

Details were provided by @drewbo :

https://8ib71h0627.execute-api.us-east-1.amazonaws.com/v1/{z}/{x}/{y}@1x?url=s3://covid-eo-data/oc3_chla_anomaly/anomaly-chla-{site_id}-{date}.tif&resampling_method={resampling_method}&bidx=1&color_map={color_map}

Where:

- z/x/y are the map tile coordinates
-     site_id is the two letter ID from https://8ib71h0627.execute-api.us-east-1.amazonaws.com/v1/sites. The exception is nas for North Adriatic Sea, which also has a second file "nas-jaxa" because both NASA and jaxa provide data in this area
-     dates have been posted in various github tickets; we're working on making this available via the API as well
-     resampling method is one of "nearest", "bilinear", or "cubic"
-     color map options are shown at

 https://8ib71h0627.execute-api.us-east-1.amazonaws.com/docs#/tiles/tile_v1__z___x___y___scale_x___ext__get

**Comment by Schpidi** [comment]
@aapopescu are you sure this is for TSM? The URL uses "oc3_chla_anomaly" instead of "spm_anomaly".

@drewbo @olafveerman what are the site IDs for Nagoya and Osaka? I can't find them from your API endpoint. For these two I also don't find the available dates. Also I can guess the extent to use but if you have the right one this would be great.

**Comment by aapopescu** [comment]
> @aapopescu are you sure this is for TSM? The URL uses "oc3_chla_anomaly" instead of "spm_anomaly".
> 
> @drewbo @olafveerman what are the site IDs for Nagoya and Osaka? I can't find them from your API endpoint. For these two I also don't find the available dates. Also I can guess the extent to use but if you have the right one this would be great.

@olafveerman , can you please provide the URL for the JAXA TSM maps?

**Comment by olafveerman** [comment]
The data was uploaded with the wrong naming schema. I'm going to process them and give you a headsup when they're up.

**Comment by aapopescu** [comment]
@Schpidi, can you please update latest dates for JAXA Chl Maps - current value is 10 June for Tokyo and 24 June for North Adriatic, should have weekly updates available, so data should go up to August already.

@olafveerman, can you please confirm this data is available? also, please ping when TSM maps from Jaxa are made available.

**Comment by Schpidi** [comment]
@aapopescu for North Adriatic there is data also on July 4th but other than this there doesn't seem to be new data available from the API.

**Comment by drewbo** [comment]
@aapopescu @Schpidi we don't have spotlight areas for Nagoya or Osaka but I assign arbitrary ids as data comes in. I also don't see water quality data for Osaka, but do see it for Kobe. I've added `ng` and `kb` ids for Nagoya and Kobe respectively.

TSM data:
- can be found at URLs like this: https://8ib71h0627.execute-api.us-east-1.amazonaws.com/v1/{z}/{x}/{y}@1x?url=s3://covid-eo-data/tsm/{spotlight_id}-{date}.tif&resampling_method=nearest&bidx=1&color_map=rdbu_r
- date/spotlight domains can be found here: https://gist.github.com/drewbo/73e7d65fda6c5edb03f7819d5a376dce
- we've just merged our new dataset discovery endpoint at https://8ib71h0627.execute-api.us-east-1.amazonaws.com/v1/datasets; it doesn't have TSM added yet but can shortly

All CHLA data has been updated for the same four sites (North Adriatic, Tokyo, Nagoya, and Kobe):
- Urls the same as previous
- date/site combinations (full bucket): https://gist.github.com/drewbo/a2decafb0f41f26f28b0d9476926eb9e
- This will also be discoverable via the same datasets API endpoint soon

**Comment by Schpidi** [comment]
thanks @drewbo! couple of observations:

CHLA
* ng and kb have blue background over land
* for nas-jaxa I had to change from anomaly-chla-nas-jaxa to anomaly-chl-nas-jaxa (removed an 'a') correct?
* for tk you have both the new and old (shifted by 3 days dates in your gist), I only used the new
* the last date for tk should be anomaly-chl-tk-2020_07_22.tif instead of anomaly-chl-tk-2020_07_25.tif shouldn't it?

TSM
* what about sf? or is SPM different than TSM?
* ng and kb have blue background over land
* is nas from JAXA or NASA? I assume JAXA right?

**Comment by drewbo** [comment]
@Schpidi:

CHLA
- I believe the blue background is incorrectly coded nodata values, I can check if there is a quick fix but otherwise we'll need new data
- yes, I switched `chla` to `chl` for consistency in the file name, sorry for the change without notification
- I'm not aware of which data is new and old but I can remove prior Tokyo dates (can you forward me the relevant email?)
- Not sure on the dates, just uploaded the full file list that I had available

TSM:
- I assumed this was different from SPM but [literature](https://earth.esa.int/pi/esa;jsessionid=65B366F9C8EEA6C8ACF563937E0475E8.jvm2?colorTheme=03&type=upload&ts=1487874372432&table=progressreport&targetIFramePage=%2Fweb%2Fguest%2Fpi-community%2Fsearch-results-and-projects%2Fapplication&cmd=image&id=7636) seems to indicate they are used interchangeably. I can (1) duplicate these in the SPM anomaly folders and (2) confirm with a science partner
- Same NoData issue
- This is from JAXA but when I duplicate in SPM I may have to add `nas-jaxa` to indicate the source (and differentiate from NASA data when there is a conflict)

**Comment by Schpidi** [comment]
also added nas (I assume from NASA) and ny as per https://github.com/NASA-IMPACT/covid-dashboard/issues/382

**Comment by Schpidi** [comment]
I've taken the tk dates from NASA-IMPACT/covid-dashboard#382. I assume the others can be removed.

I've now integrated both, SPM and TSM as advised by you and @olafveerman. I'd propose to leave as is and not change again.

**Comment by aapopescu** [comment]
@Schpidi 

Jaxa has reported the following dates are new, please update the trilateral:

- North Adriatic - CHL : ['2020-08-01'], ['2020-08-08'], ['2020-08-15']
- Tokyo - CHL: ['2020-08-01'], ['2020-08-08'], ['2020-08-15']
- Nagoya CHL: ['2020-07-25'], ['2020-08-01'], ['2020-08-08'], ['2020-08-15']
- Kobe - CHL : ['2020-07-25'], ['2020-08-01'], ['2020-08-08'], ['2020-08-15']

- North Adriatic - TSM : ['2020-08-01'], ['2020-08-08'], ['2020-08-15']
- Tokyo - TSM: ['2020-08-01'], ['2020-08-08'], ['2020-08-15']
- Nagoya TSM: ['2020-07-25'], ['2020-08-01'], ['2020-08-08'], ['2020-08-15']
- Kobe - TSM : ['2020-07-25'], ['2020-08-01'], ['2020-08-08'], ['2020-08-15']

**Comment by Schpidi** [comment]
@aapopescu these dates don't seem to be available from the NASA API yet.

@olafveerman could you please let us know once those maps are available from the API? Thanks

**Comment by Schpidi** [comment]
@olafveerman any news on the JAXA data? Thanks.

**Comment by drewbo** [comment]
@Schpidi sorry for the delay, these are updated now (all the dates and locations mentioned for CHL and TSM)

**Comment by Schpidi** [comment]
@drewbo thx for the update. one point to report, it seems 2020-07-25 is missing for both Nagoya and Kobe for both CHL and TSM. Also all maps for Nagoya and Kobe have blue no-data.

**Comment by drewbo** [comment]
@Schpidi unfortunately there isn't anything in the `covid-eo-jaxa` S3 bucket for those date/site combinations
