### ISSUE TITLE
E12c_MotorwayActivity nodata value trasnparency

### ISSUE THREAD

**Issue by AlessandroScremin** [eurodatacube/eodash#555]
Dear @gobaRules @gmilcinski @tomislijepcevic 

I ingested two datasets on EDC. E12c_MotorwayActivity and E12d_PrimaryRoads

I need to show only values data and not the no data values. (the gdal scripts used for data COG generation are these ones

**gdal_translate -of GTIFF ${filename}.tiff intermediate.tif -a_nodata -9999**
**gdaladdo -r average --config GDAL_TIFF_OVR_BLOCKSIZE 1024 intermediate.tif 2 4 8 16 32**
**gdal_translate -co TILED=YES -co COPY_SRC_OVERVIEWS=YES --config GDAL_TIFF_OVR_BLOCKSIZE 1024 -co BLOCKXSIZE=1024 -co BLOCKYSIZE=1024 -co COMPRESS=DEFLATE intermediate.tif ${filename}.tif**

What I need is to cut off or make trasparent the no data values

and used the following evalscripts to show it in colors and try to remove the no_data values (red in the first script and orange on the second) but didn't work (sse script and image related):

could you please support me in this???

//VERSION=3
 
function setup() {
return {
input: ["MotorwayActivity", "dataMask"],
output: { bands: 4,
sampleType: "UINT8" }
};
}
 
function evaluatePixel(sample) {
var nodat = sample.dataMask; 
var val = sample.MotorwayActivity;
var result= colorBlend(val,
[0,5,15,50,100],//,254 ],
[[253,243,237,0], // 0
[248,210,192,100], // 45
[236,115,82,150], // 90
[213,43,34,160], // 135
[93,19,15,170],// 180
]);
  if (nodat==1) {
    return result
  }
  else{
    return[0,0,0,0]
  }
}

with the following result 
![image](https://user-images.githubusercontent.com/65602207/94796563-3fecb580-03df-11eb-8420-55a504e907fb.png)

or also with this script that worked for water quality
//VERSION=3
function setup() {
  return {
    input: [{
      bands: ["MotorwayActivity", "dataMask"], // this sets which bands to use
    }],
    output: { // this defines the output image type
      bands: 4,
      sampleType: "UINT8"
    }
  };
}

function evaluatePixel(sample) {

  var arr = colorBlend(sample.MotorwayActivity,    [0, 10, 50, 70, 100],    [[0,0,0,],[0,0,255],[0,154,87],[251,208,99],[214,130,49] ]); 
 
  if (sample.dataMask==1)  arr.push(230);
  else arr.push(0);
  return arr;
}

image result
![image](https://user-images.githubusercontent.com/65602207/94796959-c3a6a200-03df-11eb-989f-cb46461921ce.png)

one sample of the cog is this one

[E12c_HenrikFisser_MotorwayActivity_IT_20170515.zip](https://github.com/eurodatacube/eodash/files/5311918/E12c_HenrikFisser_MotorwayActivity_IT_20170515.zip)

**Comment by gobaRules** [comment]
Hi Alessandro, 

the custom script for visualization is ok. The problem is that no_data pixels are not recognized as such in "dataMask" band. E.g.,  try this script to check which pixels are treated as no data in BYOC:
```
//VERSION=3

function setup() {
return {
input: ["MotorwayActivity", "dataMask"],
output: { bands: 4,
sampleType: "UINT8" }
};
}

function evaluatePixel(sample) {
if (sample.dataMask==1) {
   return[0, 0, 255, 150] // data pixels will be blue
  } else {
   return[255, 0, 0, 150] // no data pixels will be red
  }
}
```

Something must have gone wrong when preparing COGs (I suspect it has to do with the no_data value). Can you please send me one of the original files (a small one), so that I can check the whole COG preparation process?

**Comment by gobaRules** [comment]
Btw, you specified no_data flag as -9999 in hte process of COG preparation because you knew that the value -9999 in the original files represented no_data pixels, right?

**Comment by AlessandroScremin** [comment]
Dear Anjia thanks for feedbacks…

In attachment a small file

As occurred some time ago…the files I received have nan as no data value…so I run on all the files received the commands in the issues…and set no data as -9999 because you told me you can manage nan…


Attachment one file

Kr

Alessandro

Ps: all the image with the script below appear blue (entire image non only no data)

**Comment by gobaRules** [comment]
Hi Alessandro,

yes, now it is clear what is the problem. Using `gdal_translate ... -a_nodata -9999` doesn't change the values of pixels it only sets the tiff no_data flag to -9999. Because no_data flag is set to -9999, Sentinel Hub interprets pixels with values -9999 as no data but non of the pixels have this value (-9999) and everything is interpreted as data.

To change pixels values you need to run gdalwarp command before the rest of your commands, e.g.: 
`gdalwarp -dstnodata -9999 -of GTIFF E12c_HenrikFisser_MotorwayActivity_BG_20200515.tiff first_output.tif`

---
I do get also red pixels with the script I posted:
![image](https://user-images.githubusercontent.com/21296668/94926788-9c280600-04c1-11eb-8485-3e9a3f8033a1.png)

**Comment by gobaRules** [comment]
Perfect! Let's close this issue and resolve the overlays in https://github.com/eurodatacube/eodash/issues/557.
