### ISSUE TITLE
Errors when executing S2L1CWCSInput in Flying planes algorithm

### ISSUE THREAD

**Issue by mdelgadoblasco** [eurodatacube/eodash#577]
Dear @gmilcinski, @tomislijepcevic 

We are integrating Dr. Pamplona's algorithm for the flying airplaines indicator (E13c) and in some cases we are getting errors when using the function S2L1CWCSInput, obtaining the error as follows:

_`"During execution of task S2L1CWCSInput: index -1 is out of bounds for axis 0 with size 0"`_

This, specifically happened for the an AOI centered in 51.154091750000006,-0.18837729999999997 for the date: 2020-07-02T11:07:06

Could you please investigate which is causing this issue?

Looking at that image in the eobrowser, it seems that the data is somehow different to others as it has no quicklook, so maybe something else is happening that gives that exception to the code. You can see the image for that date without quicklook on the screenshot here below.

![image](https://user-images.githubusercontent.com/20595425/95314527-b41cd280-0891-11eb-9e88-3596c1221d36.png)

Let me know if you prefer to have a short chat with me and @AlessandroScremin so that we can explain better the experienced problem.

Thanks in advance.
Best,
Jose Manuel

**Comment by gmilcinski** [comment]
If I check this area in EO Browser, I can actually visualise the data, even though the quicklook jpg is missing. Can you try this as well? (it will be all white, as it is 100% cloudy, but you will see the data there).   
Would you be able to track the individual WCS request, that fails?  
If not, can you please send me first two blocks of your instance ID and approximate time, when the error happens, so that I try to track it in our system?

As a side note - I think it would be better to have this discussion in eodash-data github repo, which, as far as I know, is internal and we can share such information as instance IDs more openly.

**Comment by lubojr** [comment]
Solved in https://github.com/eurodatacube/eodash-data/issues/191
