### ISSUE TITLE
legend is too big on map

### ISSUE THREAD

**Issue by aapopescu** [eurodatacube/eodash#643]
Some of the legends cover up almost all of the map when map view is expanded 
Can we force the legend to not cover up more than a % of the screen?

<img width="1606" alt="Screen Shot 2020-11-06 at 16 46 34" src="https://user-images.githubusercontent.com/35488732/98385888-d2701c80-204f-11eb-8173-6408065147ca.png">

![Uploading Screen Shot 2020-11-06 at 16.47.24.png…]()

**Comment by silvester-pari** [comment]
@aapopescu agreed. Currently, it is set at 50% of the maps width, which makes sense in the right panel, but not when it is expanded. When expanded, probably something like 30% should be enough. We'll update this!
By the way, when you click on the legend, it show the actual size of the legend image.

**Comment by silvester-pari** [comment]
Fixed in https://github.com/eurodatacube/eodash/commit/e25291e8a298c04ba4d5289e90c3ca02937ade8a, you can try it on `fix-legend-size` branch.
With the current approach, it should be good for all screen sizes, only on original iPad in **portrait** mode the legend might be a tiny bit on the small side (since it is handled as large mobile phone), but iPad pro is fine. If needed, I can invest more time in this and create a special arrangement for that device.
![image](https://user-images.githubusercontent.com/26576876/98389695-b1f69100-2054-11eb-9e3e-c6ca6ab8dfa1.png)
![image](https://user-images.githubusercontent.com/26576876/98389717-bcb12600-2054-11eb-8136-91752900123b.png)![image](https://user-images.githubusercontent.com/26576876/98390172-4e209800-2055-11eb-98b5-49b6570e1526.png)
![image](https://user-images.githubusercontent.com/26576876/98390754-182fe380-2056-11eb-95f8-99e06a0121b2.png)
