### ISSUE TITLE
WQ raw data area selection chart

### ISSUE THREAD

**Issue by lubojr** [eurodatacube/eodash#784]
- add config for draw area create chart for WQ data from SH endpoint

**Comment by aapopescu** [comment]
Feedback from WQ:
- capability is good to have for WQ, but needs some adaptations, because the graph is not directly interpretable in the case of WQ (e.g. the time series do not make sense on a large area, usually this type of analyses are made on a 3.5 pixel area); the team will discuss internally to see what type of changes would be needed. 
- standby for the moment

**Comment by santilland** [comment]
Closing for now, if new developments appear, this can be reopened
